[package]
name = "fatfs"
version = "0.1.0"
edition = "2021"
description = "FatFS driver for Glenda Microkernel, supporting FAT16,FAT32 and exFAT"

[dependencies]
libglenda-rs = { path = "../../lib/libglenda-rs", features = ["rt-service"] }
